apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-base-app-networking
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-demo
  project: default
  source:
    path: base-app-networking/manifests/dev/
    repoURL: https://github.com/sinhasonalkumar/base-app-networking-k8s-state-argo-demo.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   